title: static things
description: 'try https://editor.stastic.net/#/'
social_link: twitter
social_username: williamfzc
github_repo: static
github_username: williamfzc
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /static
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
